### ISSUE TITLE
GUID надо генерировать, а не руками писать

### ISSUE THREAD

**Issue by omgiafs** [justdanpo/simply-applocker-rules#1]
Да, я знаю откуда растут ноги у этого костыля :)

Короче, вот один [batch-скрипт для генерации GUID (GUID.bat)](https://gist.github.com/davidruhmann/4207960#file-guid-bat).

Единственное - регистр букв поменять и можно пользоваться.

**Comment by justdanpo** [comment]
Если и генерировать, то так, чтобы на разных компьютерах ууиды совпадали, то бишь генерировать из хэша publishername + типа коллекции правил (чтоб для exe и msi идентификаторы не совпадали).
Менять старые идентификаторы мне кажется неправильным. Новые - пожалуйста.
Сделал пробную реализацию, но генерируются идентификаторы достаточно медленно.
Бранч autouuid https://github.com/justdanpo/simply-applocker-rules/tree/autouuid
Вместо ууида можно сделать так:

```
call :addrule "autouuid", "Yandex", "O=OOO YANDEX, L=MOSCOW, S=MOSCOW, C=RU"
```

**Comment by justdanpo** [comment]
Вариант, переделанный практически полностью на powershell
https://github.com/justdanpo/simply-applocker-rules/tree/fullpowershell

**Comment by justdanpo** [comment]
commit ca81506028330991dda4eb0dca8634c3c34983c2
