### ISSUE TITLE
Необходимо правило для софта с openprog.ru

### ISSUE THREAD

**Issue by dartraiden** [justdanpo/simply-applocker-rules#2]
На хабре подкинули [ссылку](http://openprog.ru/).
Было бы здорово, если сертификат, которым подписаны инсталляторы с этого сайта, блокировался.

CN = Inet produkt
O = Inet produkt
STREET = 44, kv.20, Pr-Kt Lenina
L = Saransk
S = The Republic of Mordovia
PostalCode = 430003
C = RU

**Comment by justdanpo** [comment]
Добавил

```
addrules "OpenProg"  "O=INET PRODUKT, L=SARANSK, S=THE REPUBLIC OF MORDOVIA, C=RU"
```
