### ISSUE TITLE
Ломается запуск metro-приложений

### ISSUE THREAD

**Issue by dartraiden** [justdanpo/simply-applocker-rules#3]
Windows 10 LTSB.

После применения bat-ника правило выглядит так:

![cp00zg5](https://cloud.githubusercontent.com/assets/5046855/24508703/f413e200-156c-11e7-9fe6-4cd597d06ef5.png)

При попытке открытия metro-приложения "Параметры" получаем сообщение "Это приложение заблокировано вашим системным администратором"

Если сделать вот так, то запускается:

![ukhts6q](https://cloud.githubusercontent.com/assets/5046855/24508729/07b2ea04-156d-11e7-8f35-934629b69f7b.png)

**Comment by justdanpo** [comment]
Пробовал на двух версиях Windows 10, повторить не удалось. Как повторить?

**Comment by dartraiden** [comment]
Только что повторил на чистой свежеустановленной в виртуалку Windows 10 Enterprise LTSB. Возможно, это происходит лишь на [LTSB](http://windowstips.ru/notes/19343), которая отличается тем, что туда поступают лишь секьюрити-фиксы, поэтому Enterprise LTSB до сих пор версии 10240. На обычной 10 Enterprise (с ноябрьским обновлением TH2) проверить не могу — после ноябрьского обновления включение службы AppID вызывает BSOD ([проблема известная](https://social.technet.microsoft.com/Forums/en-US/05d9c472-88ad-49c9-bfa7-817fef9880b6/windows-10-applocker-bug-in-1511?forum=win10itprosecurity))

Повторил так:
- gpedit.msc → Конфигурация компьютера → Конфигурация Windows → Параметры безопасности → Политики управления приложениями → AppLocker → ПКМ: Импортировать политику...
- Импортировал sarules.xml, предварительно сохранённые с помощью bat-ника
- Запустил службу AppID
- Запустил metro-приложение "Параметры" из "Пуска". Оно запустилось. На всякий случай решил проверить, работают ли правила. Попытался запустить установщик "Облака Mail.ru", запуск не удался. Снова запустил "Параметры" из "Пуска" → "Это приложение заблокировано вашим системным администратором".

**Comment by justdanpo** [comment]
В общем, достаточно было указать, что при создании правил упакованных приложений из локальных политик безопасности нет возможности задать условие по пути.
commit 2a409cec27d1bc3555306f47b9cd2e86705db872
