### ISSUE TITLE
Не создается XML в Windows 10 до версии 1607 "Creators Update".

### ISSUE THREAD

**Issue by omgiafs** [justdanpo/simply-applocker-rules#4]
Собственно, об этом уже написано в теме РуБорда.
Для нормальной работы предлагаю несколько вариантов решения:
* переписать батник / добавить отдельный батник для Win10 (или с какой версии винды там всё сломалось)
* использовать другой язык программирования для получения XML (плохо, лишний софт в системе)
* добавить к проекту актуальный XML-файл для тех, кто очень хочет трешерезку на Win10 и поэтому готов 2 минуты поработать ручками, дабы добавить правила в систему.

Проблема есть, нет смысла её замалчивать :)

**Comment by justdanpo** [comment]
Что значит не сохраняет? С ключом `saveonly` тоже? Что на экране?

**Comment by omgiafs** [comment]
Прошу пардону, сие было на версии Windows 10 до апдейта "Creators Update".
После обновления Win10 Enterprise до версии 1607 всё работает.
XML создается, служба вроде бы пытается стартануть.

При попытке запуска службы получаем ```WARNING: Cannot setup AppIDSvc ```, служба не запущена.

Тем не менее XML создается, а это главное. Надо просто обновления периодически производить :)
Данную ошибку можно закрывать.
